spring:
  application:
    name: authentication
  datasource:
    url: jdbc:mysql://localhost:3306/finance_Management
    username: root
    password: root123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET}

recilience4j:
  circuitbreaker:
    instances:
      profileServer:
        sliding-window-size : 10
        minimum-number-of-calls : 5
        failure-rate-threshold : 50
        wait-duration-in-open-state : 10s
        permited-number-of-calls-in-half-open-state : 2
