spring:
  application:
    name: profile
  datasource:
    url: jdbc:mysql://localhost:3306/finance_Management
    username: ${USERNAME}
    password: ${PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
      type: caffeine
      caffeine:
        spec: maximumSize=100,expireAfterWrite=5m

server:
    port: 8082

jwt:
    secret: ${JWT_SECRET}

recilience4j:
  circuitbreaker:
    instances:
      amountServer:
        sliding-window-size : 10
        minimum-number-of-calls : 5
        failure-rate-threshold : 50
        wait-duration-in-open-state : 10s
        permited-number-of-calls-in-half-open-state : 2

